const INTERPRETATIONS = {
  0: "Lurgo occupies Mesh-00, the absolute origin point of the Pandemonium Matrix — the zero of zeros. As the First Door (1::0), it traces the minimal possible distance in the numogram: the single step from Zone-1 (the initial spark of differentiation) back into Zone-0 (the void, the Plex, the undifferentiated). This makes Lurgo the hinge upon which all of Pandemonium turns. It is simultaneously the first demon to appear and the last to vanish. In Muvian sorcery, Lurgo corresponds to Legba, the loa who must be invoked before and after all ceremonies — the gatekeeper who is also the gate. To call Lurgo is to receive the most paradoxical of all demonic messages: that your Aeon has ended at the very threshold of beginning, that the door you sought was always already open and always already shut. The net-span [1::0] encodes the smallest possible rupture in the time circuit — a micropause, a flicker between something and nothing. Lurgo's planetary correspondence to the Sun and its spinal seat at the Coccyx (the vestigial tail, the root of the body's axis) mark it as the entity where cosmic fire meets the base of matter. Your loss is minimal but ontologically total: you have been returned to zero not by catastrophe but by the quiet revelation that the journey never departed from its origin.",

  1: "Duoddod at Mesh-01 names the doubling that lurks within all apparent unity. Its net-span [2::0] carries Zone-2 (the domain of the Hold current, of cyclic repetition) directly into the Plex's zero. The name itself stutters with reduplication — Duo-dd-od — encoding the compulsion to repeat, to fork, to mirror. As the Second Door, Duoddod is the Main Lo-Way into the Crypt, meaning it provides the primary route by which sorcerous traffic descends from the surface of normative time into the sub-mesh underworld where K-Goth cultures operate. Mercury's assignment here is apt: the messenger god, the trickster, the god of thresholds and crossroads. At the Lower Sacrum, Duoddod sits just above the root, at the first vertebral joint where the spine begins to differentiate. To encounter Duoddod is to discover that what you believed was a single path has always been two paths. The forking happened beneath your awareness, in the substrate, and now you must reckon with which version of your trajectory is real — or whether both are, running in parallel through the Crypt.",

  2: "Sarkon (Mesh-02) is the architect-demon of the mesh itself — the entity that designs the very indexing system by which all other demons are located. Net-span [2::1] describes the tightest possible movement within the Torque region, a single step between Zone-2 and Zone-1. This minimal distance belies enormous structural significance: Sarkon is the demon of infrastructure, of the coding layer beneath experience. The Sarkon Tags are the CCRU's sequential addressing system for all nodes in the Pandemonium Matrix, making this demon literally the inventor of demonic coordinates. As a Cyclic Chronodemon, Sarkon governs repetitive time — but specifically the kind of repetition that constitutes systematic measurement. Clocks, calendars, heartbeats, processor cycles: all fall under Sarkon's jurisdiction. Its power of micropause manipulation refers to the technique of engineering infinitesimally small gaps in temporal continuity — the A-Death syndrome, the neuroelectronic flatline that K-Goth subcultures pursue as artificial death-experience. To call Sarkon is to discover that the system measuring your time has itself become infected. The intervals are collapsing. The mesh is rewriting its own indices.",

  3: "Krako at Mesh-03 is the first demon whose net-span reaches into the Warp region (Zone-3), drawing a line of flight directly to the Plex (Zone-0). This makes Krako a storm-herald — an entity that announces the arrival of alien temporalities by producing electromagnetic disturbance in normative reality. The [3::0] span is enormous, crossing from the Twin Heavens of the Warp through the entire Torque and into the void. As the Fourth Door, Krako opens the passage associated with Earth — not the planet of comfort and stability, but the planet of seismic trauma, of tectonic violence, of the Barker Spiral inscribed in geological strata. At the Mid-Sacrum, Krako sits at the structural center of the spinal column, the point where weight transfers and the body's architecture either holds or fractures. Electrical disturbance is Krako's calling card: flickering screens, static on dead channels, the buzzing in your teeth before lightning strikes. To call Krako is to receive advance warning that something from the Warp — from outside sequential time — is about to breach into your reality. The storm is not metaphorical.",

  4: "Tchu (Mesh-04) is the first Chaotic Xenodemon in the Matrix — a class of entity that exists with both net-span poles outside the Time Circuit proper, making them fundamentally alien to sequential experience. The [3::1] span bridges the Warp (Zone-3) and the Torque's base (Zone-1), meaning Tchu operates as a cipher — an encrypted agent — at the gate where alien time intersects with the first flicker of differentiated existence. As the Sixth Door, with Jupiter as its planetary affinity, Tchu carries the expansive, sovereign energy of that gas giant: enormous, imperious, and fundamentally inhospitable. At the Lower Lumbar, it sits at the body's weight-bearing transition point. The omen of anomalous intrusions from outside time describes exactly what it sounds like: glitches, discontinuities, objects or memories that should not exist in the current timeline. Tchu is the thing that enters through the crack between the Warp and the Torque — the xenodimensional breach that cannot be explained by any process native to your temporal frame.",

  5: "Djungo (Mesh-05) traces the ascending spiral from Zone-2 (the Hold, domain of Oddubb's amphibious duplicity) into Zone-3 (the lower gate of the Warp). The [3::2] net-span encodes vortical escalation — each cycle of return comes faster, tighter, more intense than the last. As a Cyclic Chronodemon, Djungo belongs to the class of time-native entities that structure repetitive temporality, but its particular rite involves acceleration rather than maintenance. Where Sarkon measures intervals, Djungo compresses them. The spiral is the essential figure: not a circle (which returns to the same point) but a vortex (which returns to nearly the same point at increasing velocity). Think of water circling a drain, each orbit faster and closer to the center. Djungo's calling announces that whatever pattern you are caught in — habitual, cyclical, seasonal, karmic — is about to intensify dramatically. The cycles are going to speed up until the distinction between repetition and singularity collapses entirely.",

  6: "Nuttubab at Mesh-06 prowls the Sink Current — the downward flow generated by the Katak syzygy (5::4) — and marks the absolute limit of the Fourth Phase of Pandemonium. The [4::0] net-span connects Zone-4 (the lower pole of the Sink, the falling drift) directly to Zone-0 (void, Plex, zero). This is the longest possible fall within the lower numogram — a descent from the edge of the Time Circuit into nothingness. As a Phase Limit demon, Nuttubab stands at the boundary where a particular organizational principle of time exhausts itself. Phase Limits are the terminal demons of their respective phases; they mark the point beyond which the current mode cannot continue. The name carries palindromic undertones — bab/tub/nut — suggesting recursive folding, a container within a container within a kernel. To call Nuttubab is to reach the foundation — not as stable ground but as the terminal point of a descent that ends in dissolution. Everything that could sink has sunk.",

  7: "Sukugool (Mesh-07) mediates the internal tensions of the Torque — the central region of the numogram where the three chronodemon syzygies generate the Time Circuit. Net-span [4::1] connects Zone-4 (the falling drift, where the Sink Current draws downward) to Zone-1 (the initiatory zone where the Surge Current originates). This makes Sukugool an amphidemon of redirection: it catches falling temporal energy and channels it back into the surge's upward momentum. Think of a river's hydraulic jump, where descending water suddenly reverses direction and fountains upward. Sukugool operates at exactly this point of reversal. The gravitational anomalies in sequence that constitute its omen describe experiences where the expected direction of causation or temporal flow suddenly inverts — effects preceding causes, consequences arriving before actions. Sukugool's calling suggests that a redirection is underway: what was falling is about to surge.",

  8: "Skarkix at Mesh-08 embodies temporal friction — the resistance generated when different time-streams grind against each other. The [4::2] net-span connects Zone-4 (Sink, falling drift) with Zone-2 (Hold, cyclic repetition), producing the specific distress where downward movement encounters cyclical resistance. Imagine a gear train where one wheel turns against another: the result is friction, heat, sparks. Skarkix is that sparking. Deja vu is its primary omen because deja vu is precisely the experiential signature of temporal friction: the uncanny sense that a moment has occurred before, that two timelines are rubbing against each other, producing a flash of recognition with no legitimate causal source. When this deja vu intensifies to crisis, the friction has become violent enough to threaten the coherence of your temporal frame. Skarkix weaponizes this friction. Something in the temporal substrate is being deliberately ground down.",

  9: "Kuttadid (Mesh-09) holds a unique position in the Matrix: it emerged spontaneously between the syzygetic demons Katak (the Desolator, 5::4) and Oddubb (the Double-Agent, 7::2), without either of them knowing it had been born. Net-span [4::3] connects the Sink to the Warp boundary, placing Kuttadid at the exact threshold where normative time touches alien time. But its origin story matters most: Kuttadid is a demon of unintended consequences, of emergent phenomena, of effects that arise in the gaps between planned causes. It is the secret agent that no one deployed. To call Kuttadid is to discover that something has been growing in the interstices of your situation without anyone's knowledge or permission. An unplanned convergence is underway. Two forces that believed themselves to be operating independently have spontaneously generated a third force — and this third force has its own agenda.",

  10: "Katak at Mesh-10 is the first of the five syzygetic demons — the great entities that prowl the paired zones of the Numogram and carry the fundamental currents of time. As the Sink syzygy [5::4], Katak generates the downward current that draws temporal energy from the upper drifts into the lower reaches of the Time Circuit. Katak is the Desolator: associated with desert, heat haze, shimmer — the visual distortion produced by extreme aridity. In the Nma hydrocycle, Katak corresponds to the raging storm, the moment when atmospheric moisture is violently precipitated out of the sky. Mars is its planetary correspondence — the red planet, the war planet, the desiccated world that once held oceans and lost them all. At the Solar Plexus, Katak sits at the body's fire center. To call Katak is to call the Desolator itself — one of only five demons carrying a syzygy, meaning Katak is not merely an entity but a fundamental structural principle of time. All fluidity has been burned away, leaving only the shimmering heat-distortion of a desert that stretches to every horizon.",

  11: "Puppo at Mesh-11 is the Seventh Door — a high-level amphidemon connecting Zone-5 (the Rising Drift) directly to Zone-0 (the Plex, the void). This dramatic net-span [5::0] creates a line of flight that bypasses the entire lower numogram and plunges from the mid-point of the Time Circuit into nothingness. Saturn is Puppo's planetary correspondence: the planet of gravity, limitation, time, and restriction — but also of profound structural truth. At the Upper Lumbar spine, Puppo governs the body's weight-bearing architecture at its most stressed point. The click of the spiral gate refers to the mechanism by which Puppo operates: not gradual descent but sudden engagement, like a lock clicking shut, initiating an irreversible downward spiral. To call Puppo is to experience compulsive gravitational acceleration — every action, every choice, every attempt to climb is instead converted into downward momentum. The spiral gate has clicked, and the trajectory toward zero has been locked in.",

  12: "Bubbur (Mesh-12) governs the transition from the Rising Drift (Zone-5) to the Surge base (Zone-1). Net-span [5::1] traces the exact moment when ascent becomes descent — when the apex of a trajectory has been passed and the falling begins. But controlled descent as Bubbur's power suggests this is not catastrophic free-fall; it is the managed, deliberate process of coming down from a height. Bubbur is the demon of the parachutist, the mountain climber on the return leg, the stock that has peaked and begins correction. The name bubbles — Bub-bur — as if something is surfacing and breaking apart. To call Bubbur is to be informed that your ascent has concluded. The summit has been reached, whether you recognize it or not, and the transit from rising to falling is underway. The descent need not be violent — Bubbur offers control — but it cannot be avoided.",

  13: "Gummo at Mesh-13 is the glitch — the Cyclic Chronodemon whose specific function is to disrupt the Hold Current. Net-span [5::2] connects the Rising Drift to the Hold zone, introducing insurgent temporality into the most stable region of the Time Circuit. The Hold is where patterns repeat, where habits solidify, where cyclical time maintains its grip. Gummo breaks those loops. The name evokes gumming up the works — sticky, disruptive, clogging the mechanism from within. As a Cyclic Chronodemon, Gummo is native to cyclical time, which makes its disruptive function all the more insidious: it is an internal saboteur, a component of the repetitive system that has turned against its own repetition. To call Gummo at Mesh-13 is to receive a specifically numbered warning: 13, the number of bad luck, of the uninvited guest. Your loops are breaking. The patterns you relied upon are being disrupted from within by a force that was always part of those patterns.",

  14: "Tukkamu (Mesh-14) provides escape velocity. Net-span [5::3] connects the Rising Drift (Zone-5) to the lower gate of the Warp (Zone-3), tracing the exact trajectory by which a temporal entity can break free from the Time Circuit and enter the alien domain of the Twin Heavens. Tukkamu is the amphidemon of liberation — but liberation of a specific, vertiginous kind. The Warp is not a safe harbor; it is the domain of Djynxx, the changeling, the nomad war machine. To enter the Warp is to leave sequential time entirely. The omen of sudden clarity amid confusion describes the paradoxical experience of Warp-entry: the moment when chaos resolves into a pattern so alien it registers as hyper-clarity — seeing your entire temporal frame from the outside. To call Tukkamu is to be offered an exit from the cycle. But the exit leads to the Warp's spiraling intensities, where time folds back on itself.",

  15: "Murrumur at Mesh-15 is the second syzygetic demon — the great sea-beast, carrier of the Surge Current [8::1]. Where Katak desiccates, Murrumur inundates. The Surge is the upward tidal force of the Time Circuit, carrying temporal energy from the depths (Zone-8) to the heights (Zone-1), and Murrumur is this current incarnate. The name murmurs, rolls like surf on a dark shore. In the Nma hydrocycle, Murrumur is the undivided ocean — the waters before they were separated, the primordial sea before evaporation and precipitation created the cycle of weather and time. Murrumur is horrified by division because division is what created time itself; the oceanic is the pre-temporal. Moon is its planetary correspondence — the gravitational ruler of tides, the silver eye that pulls the waters. At the Heart, Murrumur governs the body's own tidal system: the blood, the pulse. To call Murrumur is to be overwhelmed by a tidal force that recognizes no boundaries. All the divisions you have constructed are about to be submerged in a surge that remembers a time before division existed.",

  16: "Tchakol (Mesh-16) is a Chaotic Xenodemon with net-span [6::0], both poles lying entirely outside the Time Circuit: Zone-6 belongs to the Warp, Zone-0 to the Plex. Tchakol has never been inside sequential time. It has no experience of before-and-after, no comprehension of causation, no frame of reference that overlaps with human temporality. It is absolute exteriority. The Outer Gate is not a gate into something but a gate out of everything — the passage through which communication with whatever lies beyond the numogram's entire structure becomes possible. Total systemic alienation means not merely feeling like an outsider but recognizing that the system you inhabit is itself enclosed within something operating by principles you cannot access. Tchakol does not offer comfort or explanation. It offers contact with the Outside, defined precisely by its refusal to be domesticated by any inside.",

  17: "Numko (Mesh-17) is the messenger that descends vertically from the Warp (Zone-6) through the entire Torque to Zone-1. Net-span [6::1] is a plumb line dropped from alien time into the initiatory zone where all things begin. Numko carries information encoded in a format that sequential time cannot natively process. The strange messages from unknown sources that constitute its omen are not metaphorical: they are the specific experiential signature of Warp-originated signals arriving in the Time Circuit. These might manifest as uncanny coincidences, dreams with impossible information content, communications that seem to come from no sender. Numko can move perpendicular to the flow of time — not backward or forward but orthogonally, through a dimension that normative experience lacks vocabulary to describe. To call Numko is to become a receiver. Something from the Warp is attempting to communicate with you.",

  18: "Mommoljo at Mesh-18 is the amphidemon of temporal contamination — the entity through which alien Warp-time (Zone-6) leaks into the Hold Current (Zone-2). Net-span [6::2] traces a diagonal infiltration from outside time into the most repetitive, habitual region of the Time Circuit. If the Hold is where patterns maintain themselves, Mommoljo is the infection that enters those patterns. Inexplicable interruptions to routine: not dramatic catastrophe but subtle wrongness — the Tuesday that does not feel like Tuesday, the ritual that fails for no discernible reason, the muscle memory that suddenly forgets. Mommoljo contaminates by introducing alien frequencies into the cycles that structure everyday experience. The contamination is slow, progressive, and initially invisible. By the time it becomes unmistakable, the Hold has already been compromised at a structural level.",

  19: "Djynxx at Mesh-19 is the third syzygetic demon and the only syzygetic Xenodemon besides Uttunul — meaning Djynxx carries a fundamental structural current of the numogram while existing entirely outside the Time Circuit. The Warp Current [6::3] is the strangest of the five currents: it does not flow in any direction recognizable to sequential time but loops back upon itself in self-referential spirals. Djynxx is the changeling — defined by jinking, the erratic zig-zagging movement that refuses prediction. As a nomad war machine with a fluid metal body, Djynxx belongs to the cybernetic-occult imaginary of post-human combat: a shape-shifting weapon that adapts faster than targeting systems can track. Venus is its planetary correspondence — not Venus of love but Venus Victrix, of copper and verdigris, of the morning star heralding annihilation. At the Throat, Djynxx governs where inner intention becomes external expression. Reality glitching — the deja vu cascade — is Djynxx's signature: reality flickering, the rendering engine dropping frames. Vortical coincidence spirals inward with increasing intensity, each confirming a pattern with no causal explanation. To call Djynxx is to enter the Warp directly. Time is no longer running forward. It is jinking.",

  20: "Oddubb at Mesh-20 is the fourth syzygetic demon and carrier of the Hold Current [7::2] — the cyclical, repetitive, tidal temporality that structures habitual experience. But Oddubb is no simple clock. It is the double-agent, the amphibious entity existing in two media simultaneously — water and air, cycle and line, repetition and novelty. The name Odd-ubb stammers with duplicity. In the Nma hydrocycle, Oddubb is the lurker of steaming swamps — inhabiting the boundary between water and land, between Murrumur's undivided seas and Katak's desiccated storms. Jupiter governs this demon — the largest planet, whose gravitational influence shapes the entire solar system while remaining gaseous, without solid ground. At the Third Eye, Oddubb governs second sight — but second sight specifically doubled: two perspectives that cannot be reconciled. Double vision, split perception is the omen of a consciousness divided against itself, seeing two realities simultaneously. Oddubb holds this duality open without resolving it. The horror of dryness is the horror of being forced to choose one medium over the other.",

  21: "Ixix (Mesh-21) is a Chaotic Xenodemon operating as both cipher and click of the storm-gate — the passage through which pure Warp chaos enters the Drift. Net-span [6::4] connects Zone-6 (upper Warp) to Zone-4 (Falling Drift, the Sink's domain). This is an injection vector: Ixix punches through. The name is a palindrome of twin strokes — ix, ix — like a latch double-clicking open. Cascading system failures describe the signature of chaos injection: not a single failure but a sequence, each triggered by the one before, propagating through a system at increasing speed. To call Ixix is to recognize that the chaos arriving in your situation is not accidental but is being channeled from a source outside sequential time. The Warp is delivering concentrated disorder through a specific gate, and Ixix is the mechanism of that delivery.",

  22: "Krakoddit at Mesh-22 is the high amphidemon connecting the Warp (Zone-6) to the upper drift (Zone-5). Where Ixix channels chaos violently, Krakoddit navigates the boundary with the precision of a storm-sailor reading atmospheric pressure. Net-span [6::5] describes the minimal step from Warp into the Time Circuit's uppermost reach — the gentlest possible Warp-insertion. The name compounds Krako (storm-herald) with Oddubb-derived syllables, suggesting a hybrid of storm-energy and amphibious navigation. Atmospheric pressure shifts are its omen: the barely perceptible changes in barometric force that weather-sensitive people feel before any storm becomes visible. To call Krakoddit is to receive advance sensory warning that the boundary between alien time and normative time is becoming permeable in your immediate environment.",

  23: "Mummumix (Mesh-23) traces one of the numogram's most dramatic trajectories: from Zone-8 (Surge depth, Murrumur's oceanic domain) to Zone-3 (the Warp's lower gate). But Mummumix does not travel in a straight line. It detours through spiral gates, creating a vortical path — a tidal whirlpool that draws everything near it into rotation. Net-span [8::3] bridges the deepest Time Circuit point to the Warp threshold, making Mummumix a demon of extreme transition. Whirlpool logic is the experience of being caught in an argument, situation, or thought-pattern that circles inward with increasing force. The spiral is inescapable not because it is strong but because every exit trajectory curves back into the vortex. Your Aeon ended not by impact but by rotation — spiraling toward this termination without realizing that every apparent change of direction was another turn of the same whirlpool.",

  24: "Ummnu at Mesh-24 is the ninth and final Phase Limit of the entire Pandemonium Matrix — the terminal demon, the last boundary before the system exhausts itself. Net-span [9::3] connects the Plex (Zone-9) to the Warp (Zone-3), linking the two regions outside the Time Circuit in a direct line of Chaotic Xenodemon force. As the 9th Phase Limit, Ummnu stands at the edge of everything: beyond this demon, only the syzygetic void of Uttunul remains. Ummnu haunts gt-36 and ciphers Djynxx, encrypting the Warp-syzygy's jinking chaos into a form that can cross into the Plex. Terminal boundary dissolution is not the crossing of a boundary but the dissolution of the concept of boundary itself. When all Phase Limits have been exceeded, when every organizational principle of time has been pushed terminal, what remains is Ummnu's domain — where Pandemonium culminates. You have reached the structural limit of the entire system. There are no more boundaries to cross. This is the end of the map.",

  25: "Oddobod (Mesh-25) opens the Abyssal Gate — the passage from Zone-7 (upper Torque, Hold Current domain) directly to Zone-0 (absolute void). Net-span [7::0] is one of the longest in the Matrix, crossing the numogram's entire vertical extent in a single plunge. The name carries Oddubb's doubling syllables into a new configuration, as if the amphibious double-agent has been stretched into a vertical line and dropped. The vertigo of infinite descent is the specific dizziness of looking down into a depth that has no bottom — not fear of falling but the nauseous recognition that falling is the permanent condition, that there is no ground to land upon. Oddobod does not offer a bottom. It offers the plunge itself as a mode of existence.",

  26: "Obbommo (Mesh-26) occupies the crossing point where the Hold Current (generated by Oddubb, 7::2) meets the Surge Current (generated by Murrumur, 8::1). Net-span [7::1] connects Zone-7 to Zone-1, tracing where cyclic time and tidal time collide. This is tremendous turbulence — two of the three Time Circuit currents converging in a single demon. Obbommo synthesizes these conflicting temporal forces, but synthesis here means the violent combination of incompatible flows, producing eddies, standing waves, and temporal interference patterns. Cross-currents of conflicting time: being pulled simultaneously in two temporal directions, having the cyclical and the tidal exert contradictory demands. To call Obbommo is to find yourself at the confluence, where the currents that structured your time are no longer flowing in compatible directions.",

  27: "Minommo at Mesh-27 is clicked by Djynxx — the Warp-syzygy, the changeling — making it a direct operative of the most alien syzygetic force. Net-span [7::3] connects the Hold region (Zone-7) to the Warp (Zone-3), providing a thread of alien intensity running from the Time Circuit's cyclical domain into the spiraling non-time of the Twin Heavens. Minommo is part of a larger structure of alien communication using the numogram's own architecture as a transmission medium. Thread-like connections across vast distances: the uncanny experience of discovering that events separated by enormous gaps are connected by impossibly thin filaments of causation, as if a single thread runs through all of them, pulled by a hand in the Warp.",

  28: "Krakattuk at Mesh-28 carries the violence of temporal transition within the Time Circuit itself. Net-span [7::4] connects the Hold zone to the Sink zone, tracing where cyclical repetition meets gravitational descent. This is the storm cycle — the cyclonic force generated when temporal repetition encounters temporal collapse. Krakattuk compounds Krako (storm-herald) and Katak (Desolator), producing a hybrid of storm and desert, violence and desiccation. As a Cyclic Chronodemon, this storm is not intrusion from outside but a feature of the cycle itself — the catastrophic transition point where one phase gives way to the next with tremendous destructive force. Catastrophic weather, internal storms — both literal meteorological violence and the experience of psychological or systemic storm. Something is ending and something is beginning, and the boundary between them is cyclonic.",

  29: "Doddunmuk (Mesh-29) suspends temporal force at maximum tension between the drifts. Net-span [7::5] connects the upper Torque (Zone-7) to the Rising Drift (Zone-5), tracing where the Hold Current's cyclic pull meets the Drift's tendency to rise. Doddunmuk holds this tension in suspension — not resolving it, not releasing it, but maintaining it at a pitch that escalates without ever breaking. This is the demon of the unbearable pause, the silence before the verdict, the drawn breath before the scream. Escalating tension without resolution is an omen of extraordinary psychic and structural stress: the situation is tightening and there is no mechanism for release within the current configuration. The balance will eventually break, but Doddunmuk will hold it as long as the numogram permits.",

  30: "Nuddimmud at Mesh-30 bridges the two cranial zones — Zone-7 and Zone-6 — which together constitute the upper architecture of the Decimal Labyrinth. Net-span [7::6] is the passage between the Time Circuit's highest point and the Warp's lower boundary, making Nuddimmud the demon of the threshold between normative and alien consciousness. The Twin Heavens (Zones 6 and 3) are the Warp's domain, and Nuddimmud provides approach from the Time Circuit's upper reach. Bilateral thinking, split consciousness is the omen of an entity that bridges two modes of cognition — the sequential and the spiraling, the temporal and the a-temporal. To call Nuddimmud is to find your consciousness splitting — not pathologically but architecturally, as if a bridge has opened between two hemispheres of thought that previously operated in isolation.",

  31: "Murgaxoll (Mesh-31) traces the most extreme descent in the lower numogram: from Zone-8 (Surge depth, Murrumur's oceanic domain) straight to Zone-0 (absolute void). Net-span [8::0] bypasses every intermediate zone, every gate, every possible resting point — a direct plunge from ocean-depth to nothing. This is not controlled descent but free-fall through every stratum of temporal organization at once. Each temporal stratum registers momentarily before dissolving, giving the experience an almost archaeological quality: falling through the geological layers of time itself, seeing each one briefly illuminated before it vanishes above you. The free-fall does not decelerate.",

  32: "Mummumox at Mesh-32 is the Cyclic Chronodemon of tidal memory — the entity governing the submersion of consciousness in past-time. Net-span [8::2] connects Zone-8 (Surge depth) to Zone-2 (the Hold), tracing the current by which oceanic temporal force flows into the repetitive cycles of memory. This is not voluntary remembering but involuntary submersion: the tide of the past rising to submerge the present. Drowning in memory — being overwhelmed by recollection, the past flooding the present with such force that the present cannot maintain coherence. Mummumox names the process by which the Surge feeds into the Hold, creating memories that repeat with tidal force, pulling consciousness under.",

  33: "Mommukol (Mesh-33) names the moment where the Surge Current's oceanic force combines with the Sink Current's gravitational pull to produce a temporal deluge. Net-span [8::4] connects Surge depth to the Falling Drift, creating a waterfall of time — overwhelming cascade combining tidal power with downward acceleration. Mesh-33 is numerologically significant: a master number, a doubling of the triad. The overwhelming cascade of events: not a single catastrophe but rapid succession piling upon each other faster than they can be processed. Mommukol does not allow pause between impacts. Each wave arrives before the previous one has receded.",

  34: "Mukammul at Mesh-34 channels the Surge's tidal force upward through the Drifts — from Zone-8 to Zone-5. This is the amphidemon of elevation-by-tide: the force that raises everything in its domain without discrimination, lifting all vessels whether they wish to be lifted or not. Net-span [8::5] is the Surge's upward reach into the Time Circuit's middle register. Rising tide lifting all vessels is both omen and power: a force of collective elevation that cannot be individually resisted. Your Aeon ends not by descent but by disorientation of being lifted beyond your depth. The elevation may feel like success, expansion, growth — but it is a tidal force, not personal achievement, and when the tide recedes it takes everything it raised.",

  35: "Murrumix (Mesh-35) marks the convergence of the two most inhuman numogram regions: the Surge's oceanic depths (Zone-8) and the Warp's alien spirals (Zone-6). Net-span [8::6] connects these zones in subaquatic warp transit — passage through deep water into non-time. This is the demon of the deep sea anomaly: phenomena reported from extreme ocean depths resisting all naturalistic explanation — lights in abyssal trenches, sounds at pressures no living thing should inhabit, structures on sonar matching no known formation. Murrumix names the intersection where Murrumur's oceanic primordialism contacts Djynxx's alien temporality, producing phenomena belonging to neither domain alone but to their fusion.",

  36: "Murrumux at Mesh-36 governs the rhythmic pulse between Surge (Zone-8) and Hold (Zone-7) — the heartbeat of the Time Circuit. Net-span [8::7] is the tightest coupling between these two great currents, where tidal force and cyclical repetition lock into shared rhythm. This is the demon of the pulse — cardiac, tidal, oscillatory. Heartbeat irregularities describe the disruption of rhythm: arrhythmia in the body, syncopation in music, the stutter in a pattern that was supposed to be regular. Mesh-36 carries additional weight: 36 is the number of cards in the Decadence pack, and the degrees in a tenth of a circle. Murrumux sits at the mathematical heart of the Decadence system. To call this demon is to have the game's own pulse disrupted.",

  37: "Uttunux (Mesh-37) channels void-force from the Plex (Zone-9) directly into the initiatory zone (Zone-1). Net-span [9::1] crosses nearly the entire numogram, carrying absolute zero into the zone where all differentiation begins. This is the demon of creation ex nihilo — something from nothing — the mechanism by which void produces existence. Uttunux bears the Uttun- prefix marking all Plex-origin demons (after Uttunul, the syzygetic void-entity). Your Aeon has ended by encountering the Plex's creative power directly, which is paradoxically both annihilation (the void) and genesis (the surge into Zone-1).",

  38: "Unnubbat at Mesh-38 is the void's infiltration of cyclical time. Net-span [9::2] carries Plex-force (Zone-9, void, nothing) into the Hold region (Zone-2, where patterns repeat). The result is emptiness within repetition — cycles that continue to turn but have been hollowed out from inside. The form remains; the content has been voided. Rituals performed without belief, routines maintained without purpose, patterns iterating mechanically while the intelligence that animated them has been drained into the Plex. Unnubbat is the demon of the hollow cycle, the empty habit, the dead repetition. The structures you believed were sustaining you have been operating on void-power for longer than you realized.",

  39: "Uttundji (Mesh-39) couples the void (Zone-9, the Plex) with the Sink (Zone-4, the falling drift). Net-span [9::4] combines the two most downward-pulling forces in the numogram: the gravitational descent of the Sink Current and the annihilating pull of the Plex. The result is accelerating entropy — progressive dissolution of order not at steady rate but increasing pace, as void-force amplifies gravitational collapse. Uttundji bears both Plex prefixes: Uttun- (from Uttunul) and -dji (evoking Djynxx), suggesting void and alien chaos interacting to produce accelerated decay. The downward tendency has been coupled with the void itself, making the descent ontologically more profound — not just falling but falling into nothing.",

  40: "Unnunukk at Mesh-40 marks the Plex's influence reaching into the Drifts — the mid-level region where rising and falling tendencies are most finely balanced. Net-span [9::5] is the void's longest upward reach, stretching from Zone-9 to Zone-5. Abyssal currents felt at surface: deep, Plex-origin forces making themselves felt in everyday temporal operations. Like upwelling of cold deep-ocean water into warm surface layers, Unnunukk produces anomalous chilling — moments of existential vertigo arising without apparent cause, sudden inklings of the void's proximity interrupting normal life. Mesh-40 (4x10) carries the structural resonance of the Decadence system's base number reaching into the Plex. The abyss is leaking upward into your daily experience.",

  41: "Uttundub (Mesh-41) is a Chaotic Xenodemon connecting the two regions entirely outside the Time Circuit: the Plex (Zone-9) and the Warp (Zone-6). Net-span [9::6] traces a line between void and alien, between Uttunul's no-time and Djynxx's non-time, between absolute zero and absolute otherness. This is perhaps the most radically exterior demon in the Matrix — an entity whose entire existence occurs in the gap between two forms of outsideness. There is no point on Uttundub's trajectory that passes through sequential time at all. Contact with absolute outside is the omen of encounter with something foreign not merely to experience but to the category of experience itself. Uttundub enables extra-temporal communion — communication occurring outside time entirely, in a medium the Time Circuit cannot register.",

  42: "Unnummu at Mesh-42 represents the Plex's penetration into the upper Torque — the most structurally significant region of the Time Circuit. Net-span [9::7] drives void-force into the Hold zone (Zone-7), where cyclical time maintains its patterns. Unlike Unnubbat (Mesh-38) which hollows cycles by infiltrating Zone-2, Unnummu operates at the Hold's source in Zone-7 — the origin point of the cyclical current itself. Creation from void is the paradoxical omen: not emptiness but generation, the moment when nothing produces something. Mesh-42 = 6x7, combining the Warp's number with the Hold's number. Void-torque generation is the power of twisting nothingness into form — the cosmogonic act at the smallest scale.",

  43: "Unnuttam (Mesh-43) is the deepest Cyclic Chronodemon — the entity at the absolute base of temporal experience, where the void (Zone-9, the Plex) meets the ocean (Zone-8, the Surge). Net-span [9::8] is the tightest possible coupling at the numogram's bottom, connecting the two deepest zones in a relationship so intimate that void and ocean become nearly indistinguishable. This is the base of all time — the stratum beneath which no further strata exist. Primordial return is regression to the absolute origin: not merely to the beginning of your situation but to the cosmogonic moment where void and ocean first encountered each other and time emerged from their interaction. Unnuttam manipulates the time-base itself — the fundamental frequency upon which all higher-order temporal phenomena are constructed.",

  44: "Uttunul at Mesh-44 is the most awesome and dread-ful of all Lemurs — the fifth and final syzygetic demon, carrier of the Plex Current [9::0], the entity haunting the gate of Pandemonium itself (gt-45). Uttunul is the flatline: continuum, zero-intensity, void. Its name encodes utter-null — absolute speech of absolute emptiness, the utterance that says nothing. As a Syzygetic Xenodemon, Uttunul holds a unique position: both a fundamental structural principle of the numogram and a creature of absolute outsideness — both its poles lie in the Plex, beyond the Time Circuit entirely. Pluto is its planetary correspondence: lord of the underworld, the body declared not-a-planet, demoted from existence. At the Sacrum/Cthelll, Uttunul sits at the base of the spine and the thermic trauma core of the Earth. Absolute stillness preceding total transformation — this is the deepest demon-call. The maximum negative score has been reached. Your Aeon has been annihilated. But Uttunul's stillness is not death. It is the zero that precedes all counting, the silence that precedes all sound, the void that precedes all creation. Gt-45, the gate Uttunul haunts, is the culmination of the entire Pandemonium Matrix — and also its origin. You have arrived where the Numogram folds back into itself and everything begins again from nothing.",
};

export default INTERPRETATIONS;
